// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>MTG App</title><script>\n            console.log(\"Loading htmx.min.js from /static/htmx.min.js\");\n        </script><script src=\"/static/htmx.min.js\"></script><link href=\"/static/output.css\" rel=\"stylesheet\"></head><body class=\"bg-gray-100 text-gray-900\"><header class=\"bg-blue-600 text-white p-4\"><h1 class=\"text-3xl font-bold\">Welcome to MTG Deck Builder!</h1><nav><ul class=\"flex space-x-4 mt-2\"><li><a href=\"/login\" hx-get=\"/login\" hx-target=\"body\" hx-swap=\"innerHTML\" class=\"hover:text-gray-200\">Login</a></li><li><a href=\"/signup\" hx-get=\"/signup\" hx-target=\"body\" hx-swap=\"innerHTML\" class=\"hover:text-gray-200\">Sign Up</a></li></ul></nav></header><main class=\"flex flex-col items-center mt-8\"><div class=\"bg-white p-6 rounded-lg shadow-lg text-center max-w-lg\"><p>With this app, you can create, edit, and delete your own card decks for Magic the Gathering. Integrating with the Scryfall API allows you to search for and add any Magic the Gathering card to your deck with ease. You can also remove cards from your deck and make changes to it whenever you'd like.</p></div><p class=\"mt-4\">Sign up now to start building your ultimate deck!</p></main><footer class=\"bg-gray-200 text-center p-4 mt-8 w-full\"><p>© 2024 MTG App</p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
